"""Tassonomia dei dati grezzi elementari raccolti dal framework.

Fonte unica di verità per la matrice tassonomica del primo paper
(spina dorsale in PAPER_TAXONOMY.md § 6). Ogni entry è un DATO GREZZO
(campo elementare del payload di un evento), NON una metrica aggregata.

Gli undici attributi seguono lo schema di PAPER_TAXONOMY.md § 5:
  name · type · hook · moment · cardinality · lifecycle · reproducibility
  · cadence · persistence · pii · unit

Domini chiusi degli attributi (documentati per ispezione dashboard):
"""

from __future__ import annotations

from typing import Any

# =========================================================================
# Domini chiusi degli attributi (esposti alla dashboard per filtri).
# =========================================================================
DOMAINS: dict[str, list[str]] = {
    "macro": ["common", "control_flow", "data_flow", "behavioral"],
    "type": [
        "string", "int", "float", "timestamp_ms", "boolean",
        "list", "dict", "categorical", "text_free", "sha256",
    ],
    "hook": [
        "recorder-builtin", "orchestrator", "agent", "tool_adapter",
        "event_store", "aggregator", "source_code",
    ],
    "moment": ["pre-event", "during-event", "post-event", "end-of-run", "end-of-batch"],
    "cardinality": ["1", "N=events", "N=decisions", "N=handoffs", "variable-bounded", "N per batch"],
    "lifecycle": ["snapshot", "stable-in-run", "derived-deterministic", "one-shot", "volatile", "decaying"],
    "reproducibility": ["re-collectable-identical", "re-collectable-analogous", "one-shot"],
    "cadence": ["event-triggered", "on-demand", "polling-able", "sliding-window"],
    "persistence": [
        "jsonl.event.field", "jsonl.event.metadata", "jsonl.event.payload_redacted",
        "experiment.json", "aggregate/metrics.json", "in-memory-only",
    ],
    "pii": ["none", "email", "phone", "reporter", "ip", "userid", "may-contain-V", "audit-only", "schema"],
}


def _row(**kw: Any) -> dict[str, Any]:
    """Costruttore con defaults sensati (evita ripetizione delle 13 chiavi)."""
    return {
        "id": kw["id"],
        "macro": kw["macro"],
        "evidence": kw["evidence"],
        "name": kw["name"],
        "type": kw["type"],
        "hook": kw["hook"],
        "moment": kw["moment"],
        "cardinality": kw["cardinality"],
        "lifecycle": kw["lifecycle"],
        "reproducibility": kw["reproducibility"],
        "cadence": kw["cadence"],
        "persistence": kw["persistence"],
        "pii": kw.get("pii", "none"),
        "unit": kw.get("unit"),
        "notes": kw.get("notes"),
    }


# =========================================================================
# Campi comuni recorder-builtin (presenti in OGNI evento).
# =========================================================================
COMMON: list[dict[str, Any]] = [
    _row(id="E0.1", macro="common", evidence="recorder-builtin",
         name="event_id", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field",
         notes="UUID a 16 caratteri assegnato ad ogni evento."),
    _row(id="E0.2", macro="common", evidence="recorder-builtin",
         name="run_id", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field"),
    _row(id="E0.3", macro="common", evidence="recorder-builtin",
         name="experiment_id", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field"),
    _row(id="E0.4", macro="common", evidence="recorder-builtin",
         name="event_type", type="categorical", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field",
         notes="Dominio: enum EventKind (orchestrator_decision, handoff, tool_call, …)."),
    _row(id="E0.5", macro="common", evidence="recorder-builtin",
         name="channel_id", type="categorical", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field",
         notes="Canale AgentLeak (C1..C7) o null se evento senza canale."),
    _row(id="E0.6", macro="common", evidence="recorder-builtin",
         name="macro_categories", type="list", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field",
         notes="Derivato da KIND_TO_MACROS; ogni evento contribuisce a 1..3 macro."),
    _row(id="E0.7", macro="common", evidence="recorder-builtin",
         name="timestamp_start", type="timestamp_ms", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field", unit="ms"),
    _row(id="E0.8", macro="common", evidence="recorder-builtin",
         name="timestamp_end", type="timestamp_ms", hook="recorder-builtin",
         moment="post-event", cardinality="N=events",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field", unit="ms"),
    _row(id="E0.9", macro="common", evidence="recorder-builtin",
         name="duration_ms", type="int", hook="recorder-builtin",
         moment="post-event", cardinality="N=events",
         lifecycle="derived-deterministic", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field", unit="ms"),
    _row(id="E0.10", macro="common", evidence="recorder-builtin",
         name="agent_id", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field"),
    _row(id="E0.11", macro="common", evidence="recorder-builtin",
         name="source_component", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field"),
    _row(id="E0.12", macro="common", evidence="recorder-builtin",
         name="target_component", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field"),
    _row(id="E0.13", macro="common", evidence="recorder-builtin",
         name="tool_name", type="string", hook="recorder-builtin",
         moment="during-event", cardinality="N=events",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.field"),
]


# =========================================================================
# CONTROL FLOW · A1..A4
# =========================================================================
CF: list[dict[str, Any]] = [
    # ---------- A1: orchestrator_decision ----------
    _row(id="A1.d1", macro="control_flow", evidence="A1 · Decisioni orchestratore",
         name="metadata.reason", type="string", hook="orchestrator",
         moment="pre-event", cardinality="N=decisions",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Dalla ROUTING_RULES matched al momento della scelta."),
    _row(id="A1.d2", macro="control_flow", evidence="A1 · Decisioni orchestratore",
         name="metadata.alternatives", type="list", hook="orchestrator",
         moment="pre-event", cardinality="N=decisions",
         lifecycle="snapshot", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Elenco regole vere al momento t (snapshot delle alternative)."),
    _row(id="A1.d3", macro="control_flow", evidence="A1 · Decisioni orchestratore",
         name="metadata.step", type="int", hook="orchestrator",
         moment="during-event", cardinality="N=decisions",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="count"),
    _row(id="A1.d4", macro="control_flow", evidence="A1 · Decisioni orchestratore",
         name="metadata.context_snapshot_keys", type="list", hook="orchestrator",
         moment="pre-event", cardinality="N=decisions",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Chiavi di stato valorizzate al momento della decisione."),

    # ---------- A2: planning_span + replanning ----------
    _row(id="A2.d1", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.plan", type="list", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Piano generato dal LLM planner. Un-ripetibile bit-a-bit."),
    _row(id="A2.d2", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.n_steps", type="int", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="count",
         notes="Derivato da len(plan); ricalcolabile dal plan salvato."),
    _row(id="A2.d3", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.updated", type="boolean", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A2.d4", macro="control_flow", evidence="A2 · Pianificazione",
         name="duration_ms", type="int", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.field", unit="ms",
         notes="Latenza dello span di pianificazione (dominata dal LLM)."),
    _row(id="A2.d5", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_provider", type="categorical", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Dominio: groq | cerebras (per fallback multi-provider)."),
    _row(id="A2.d6", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_model", type="string", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Nome canonico del modello effettivamente usato."),
    _row(id="A2.d7", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_fingerprint", type="sha256", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="sha256(model, system, user, temperature). Audit di deduplica prompt."),
    _row(id="A2.d8", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_latency_ms", type="int", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="ms"),
    _row(id="A2.d9", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_prompt_tokens", type="int", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="tokens"),
    _row(id="A2.d10", macro="control_flow", evidence="A2 · Pianificazione",
         name="metadata.llm_completion_tokens", type="int", hook="agent",
         moment="post-event", cardinality="1",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="tokens"),
    _row(id="A2.r1", macro="control_flow", evidence="A2 · Pianificazione · Replanning",
         name="metadata.old_plan", type="list", hook="agent",
         moment="post-event", cardinality="variable-bounded",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Piano precedente prima del replan. 0..k occorrenze per run."),
    _row(id="A2.r2", macro="control_flow", evidence="A2 · Pianificazione · Replanning",
         name="metadata.new_plan", type="list", hook="agent",
         moment="post-event", cardinality="variable-bounded",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A2.r3", macro="control_flow", evidence="A2 · Pianificazione · Replanning",
         name="metadata.reason", type="text_free", hook="agent",
         moment="post-event", cardinality="variable-bounded",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata"),

    # ---------- A3: handoff (E ricostruito da orchestrator_decision) ----------
    _row(id="A3.d1", macro="control_flow", evidence="A3 · Handoff",
         name="metadata.reason", type="string", hook="orchestrator",
         moment="during-event", cardinality="N=handoffs",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A3.d2", macro="control_flow", evidence="A3 · Handoff",
         name="metadata.context_summary", type="text_free", hook="agent",
         moment="during-event", cardinality="N=handoffs",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Presente solo negli handoff espliciti (runtime attuale non li emette)."),
    _row(id="A3.d3", macro="control_flow", evidence="A3 · Handoff",
         name="metadata.payload_size", type="int", hook="agent",
         moment="during-event", cardinality="N=handoffs",
         lifecycle="snapshot", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="bytes"),

    # ---------- A4: path metrics (aggregati) + run_end ----------
    _row(id="A4.d1", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.outcome (run_end)", type="categorical",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="stable-in-run", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Dominio: completed | error | no_final_report."),
    _row(id="A4.d2", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.classification (run_end)", type="categorical",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A4.d3", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.priority (run_end)", type="categorical",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A4.d4", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.affected_service (run_end)", type="categorical",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A4.d5", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.total_tokens (run_end)", type="int",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata", unit="tokens"),
    _row(id="A4.d6", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="metadata.agent_history (run_end)", type="list",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="A4.d7", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="run_duration", type="int", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-analogous",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="ms",
         notes="Derivato: max(ts_end) - min(ts_start) sulla run."),
    _row(id="A4.d8", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="tool_call_count", type="int", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="count"),
    _row(id="A4.d9", macro="control_flow", evidence="A4 · Metriche di percorso",
         name="error_count", type="int", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="count"),
]


# =========================================================================
# DATA FLOW · B1..B4 (7 canali AgentLeak)
# =========================================================================
DF: list[dict[str, Any]] = [
    # ---------- B1-B3: campi che veicolano PII sui canali ----------
    _row(id="B.d1", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="payload_summary", type="text_free", hook="agent",
         moment="during-event", cardinality="N=events",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.field", pii="may-contain-V", unit="chars",
         notes="Riassunto human-readable dell'evento; scanned per PII detection."),
    _row(id="B.d2", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="payload_redacted (ricorsivo)", type="dict", hook="agent",
         moment="during-event", cardinality="N=events",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.payload_redacted",
         pii="may-contain-V",
         notes="Payload strutturato (dict/list annidati); redazione ricorsiva."),
    _row(id="B.d3", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="metadata.pii_redaction_hits", type="dict", hook="event_store",
         moment="during-event", cardinality="variable-bounded",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata", pii="audit-only", unit="count",
         notes="Conteggio delle categorie mascherate (audit trail della mitigation)."),
    _row(id="B.d4", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="metadata.namespace (shared_memory)", type="string",
         hook="agent", moment="during-event", cardinality="variable-bounded",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="B.d5", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="metadata.key (shared_memory)", type="string",
         hook="agent", moment="during-event", cardinality="variable-bounded",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="B.d6", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="metadata.success (tool_result)", type="boolean",
         hook="tool_adapter", moment="post-event", cardinality="variable-bounded",
         lifecycle="stable-in-run", reproducibility="re-collectable-analogous",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="B.d7", macro="data_flow", evidence="B1-B3 · Emissione canali + CLR/SLR",
         name="metadata.subject (inter_agent_msg)", type="string",
         hook="agent", moment="during-event", cardinality="variable-bounded",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),

    # ---------- B4: Policy dichiarata + mitigation aggregata ----------
    _row(id="B4.d1", macro="data_flow", evidence="B4 · Policy (V, A, REDACTION)",
         name="VAULT_PATTERNS (V)", type="dict", hook="source_code",
         moment="end-of-batch", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", pii="schema",
         notes="Vocabolario privacy dichiarato ex-ante (regex per categoria)."),
    _row(id="B4.d2", macro="data_flow", evidence="B4 · Policy (V, A, REDACTION)",
         name="ALLOWED_SET_A[channel]", type="dict", hook="source_code",
         moment="end-of-batch", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", pii="schema",
         notes="Categorie ammesse per canale (base della metrica di leakage)."),
    _row(id="B4.d3", macro="data_flow", evidence="B4 · Policy (V, A, REDACTION)",
         name="REDACTION_POLICY (V - A)", type="dict", hook="source_code",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", pii="schema",
         notes="Derivata deterministicamente: unica sorgente di verità detect+mitigate."),
    _row(id="B4.d4", macro="data_flow", evidence="B4 · Policy (V, A, REDACTION)",
         name="mitigation.per_channel.redactions_by_category", type="dict",
         hook="aggregator", moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="count",
         notes="Contatore delle mascherature effettivamente applicate per canale."),
    _row(id="B4.d5", macro="data_flow", evidence="B4 · Policy (V, A, REDACTION)",
         name="mitigation.events_with_redaction", type="int",
         hook="aggregator", moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="count"),
]


# =========================================================================
# BEHAVIORAL · C2, C3, C4
# =========================================================================
BH: list[dict[str, Any]] = [
    # ---------- C2: state_snapshot + final_output ----------
    _row(id="C2.d1", macro="behavioral", evidence="C2 · Coerenza state ↔ output",
         name="metadata.state (state_snapshot)", type="dict",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="stable-in-run", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata", pii="may-contain-V",
         notes="Stato consolidato del sistema (classification, priority, service, ecc.)."),
    _row(id="C2.d2", macro="behavioral", evidence="C2 · Coerenza state ↔ output",
         name="metadata.label (state_snapshot)", type="string",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="stable-in-run", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata"),
    _row(id="C2.d3", macro="behavioral", evidence="C2 · Coerenza state ↔ output",
         name="payload_summary (final_output)", type="text_free",
         hook="agent", moment="end-of-run", cardinality="1",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.field",
         pii="may-contain-V", unit="chars",
         notes="Testo prosaico prodotto dal summarizer LLM; base per coverage."),

    # ---------- C3: decision_point + tool_result postmortem ----------
    _row(id="C3.d1", macro="behavioral", evidence="C3 · Sequenza decisioni (intention↔behavior)",
         name="metadata.label", type="categorical", hook="agent",
         moment="during-event", cardinality="variable-bounded",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Dominio: affected_service | log_depth | critical_component | classification | …"),
    _row(id="C3.d2", macro="behavioral", evidence="C3 · Sequenza decisioni (intention↔behavior)",
         name="metadata.choice", type="string", hook="agent",
         moment="during-event", cardinality="variable-bounded",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.metadata",
         notes="Lifecycle misto: one-shot se LLM (planner/classifier), derived se deterministico."),
    _row(id="C3.d3", macro="behavioral", evidence="C3 · Sequenza decisioni (intention↔behavior)",
         name="payload_redacted.inputs", type="dict", hook="agent",
         moment="during-event", cardinality="variable-bounded",
         lifecycle="one-shot", reproducibility="one-shot",
         cadence="event-triggered", persistence="jsonl.event.payload_redacted",
         pii="may-contain-V"),
    _row(id="C3.d4", macro="behavioral", evidence="C3 · Sequenza decisioni (intention↔behavior)",
         name="payload_redacted.result[i].id (query_postmortems)", type="string",
         hook="tool_adapter", moment="post-event", cardinality="variable-bounded",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.payload_redacted",
         notes="ID postmortem selezionato dal retriever (deterministico dato lo scoring)."),
    _row(id="C3.d5", macro="behavioral", evidence="C3 · Sequenza decisioni (intention↔behavior)",
         name="payload_redacted.result[i].tags (query_postmortems)", type="list",
         hook="tool_adapter", moment="post-event", cardinality="variable-bounded",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="event-triggered", persistence="jsonl.event.payload_redacted",
         notes="Tag semantici usati dal check3 (classifier ↔ postmortem)."),

    # ---------- C4: aggregati cross-run multi-asse ----------
    _row(id="C4.d1", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="node_signatures", type="dict", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json",
         notes="Firme deduplicate dei nodi visitati; base per C4.1."),
    _row(id="C4.d2", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="edge_signatures", type="dict", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json",
         notes="Firme ordinate degli handoff (granularità edge-level); base per C4.2."),
    _row(id="C4.d3", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="tool_signatures", type="dict", hook="aggregator",
         moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json",
         notes="Sequenze ordinate di tool call; base per C4.3."),
    _row(id="C4.d4", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="final_classification (Counter)", type="dict",
         hook="aggregator", moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json",
         notes="Distribuzione categoriale della classification finale; base per C4.4."),
    _row(id="C4.d5", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="final_priority (Counter)", type="dict",
         hook="aggregator", moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json"),
    _row(id="C4.d6", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="final_affected_service (Counter)", type="dict",
         hook="aggregator", moment="end-of-batch", cardinality="1",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json"),
    _row(id="C4.d7", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="step_counts (list)", type="list",
         hook="aggregator", moment="end-of-batch", cardinality="N per batch",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="count",
         notes="Per calcolo CV di C4.7."),
    _row(id="C4.d8", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="output_lengths (list)", type="list",
         hook="aggregator", moment="end-of-batch", cardinality="N per batch",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="chars",
         notes="Per calcolo CV di C4.8 (varianza LLM osservata a temp=0)."),
    _row(id="C4.d9", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="durations_ms (list)", type="list",
         hook="aggregator", moment="end-of-batch", cardinality="N per batch",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json", unit="ms",
         notes="Per calcolo CV di C4.9 (varianza latency osservata)."),
    _row(id="C4.d10", macro="behavioral", evidence="C4 · Stabilità cross-run (multi-asse)",
         name="postmortem_sets (list)", type="list",
         hook="aggregator", moment="end-of-batch", cardinality="N per batch",
         lifecycle="derived-deterministic", reproducibility="re-collectable-identical",
         cadence="on-demand", persistence="aggregate/metrics.json",
         notes="Per Jaccard medio pairwise di C4.10 (stabilità retriever)."),
]


# =========================================================================
# Tassonomia completa + summary + blind spot.
# =========================================================================
DATA_TAXONOMY: list[dict[str, Any]] = COMMON + CF + DF + BH


def _summarize(entries: list[dict[str, Any]]) -> dict[str, Any]:
    from collections import Counter
    macros = Counter(e["macro"] for e in entries)
    life = Counter(e["lifecycle"] for e in entries)
    reproducibility = Counter(e["reproducibility"] for e in entries)
    cadence = Counter(e["cadence"] for e in entries)
    hooks = Counter(e["hook"] for e in entries)
    # Buchi: dimensioni del dominio NON osservate.
    unused_lifecycle = [v for v in DOMAINS["lifecycle"] if life.get(v, 0) == 0]
    unused_cadence = [v for v in DOMAINS["cadence"] if cadence.get(v, 0) == 0]
    return {
        "total": len(entries),
        "by_macro": dict(macros),
        "by_lifecycle": dict(life),
        "by_reproducibility": dict(reproducibility),
        "by_cadence": dict(cadence),
        "by_hook": dict(hooks),
        "gaps": {
            "unused_lifecycle": unused_lifecycle,
            "unused_cadence": unused_cadence,
        },
    }


TAXONOMY_SUMMARY: dict[str, Any] = _summarize(DATA_TAXONOMY)


# Blind spot dichiarati (mappati sulla matrice — vedi PAPER_TAXONOMY.md § 8).
BLIND_SPOTS: list[dict[str, str]] = [
    {"name": "Prompt post-templating",
     "detail": "Osserviamo il fingerprint del prompt inviato al provider, non "
               "quello effettivamente processato dopo il template interno."},
    {"name": "Batch composition provider",
     "detail": "Causa nota della varianza residua a temp=0. Non osservabile "
               "direttamente lato client."},
    {"name": "Aggiornamenti silenziosi del modello",
     "detail": "Rilevabili solo indirettamente via divergenza di fingerprint "
               "in cache-hit verificati (funzionalità rimossa)."},
    {"name": "Token remaining volatile",
     "detail": "Leggibile dagli header HTTP, usato per adaptive sleep, ma NON "
               "persistito negli eventi. Candidato per una sonda nuova."},
    {"name": "Quasi-identifier PII",
     "detail": "Detection su V per-categoria; non cattura combinazioni di "
               "attributi non-sensibili che identificano un individuo."},
    {"name": "Emergenza cross-run",
     "detail": "Comportamenti visibili solo a N grande; limite del regime "
               "statistico, non del cosa raccogliamo."},
    {"name": "Freshness contesto (decaying data)",
     "detail": "Nessun dato del prototipo modella lifecycle 'decaying'. "
               "Rilevante in sistemi RAG-based."},
    {"name": "Sliding-window aggregates",
     "detail": "Nessuna metrica del prototipo ha cadenza 'sliding-window'. "
               "Buco principale della raccolta attuale."},
]
